name : simple_cicd

on:
    push:
        branches:
            - main

jobs:
    checkout-code:
        runs-on: ubuntu-Latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: run
          run: |
              ls
              whoami

        - name: copy file via ssh password
          uses: appleboy/scp-action@v0.1.7
          with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.KEY }}
              port: ${{ secrets.PORT }}
              source: "./"
              target: /home/ubuntu

        

        
               

